# Tugas Besar 1C IF3270 - Machine Learning
------------------------------------------
##### NIM/Nama  : 13517014/Yoel Susanto | 13517065/Andrian Cedric | 13517131/Jan Meyer Saragih | 13517137/Vincent Budianto
##### Nama file : Tubes1C_13517014.ipynb
##### Topik     : Implementasi modul myMLP
##### Tanggal   : 28 February 2020
------------------------------------------

In [1]:
from Layer import Layer, ActivationFunction
from MLP import MLP
from sklearn.neural_network import MLPClassifier as skMLP
from sklearn import metrics

import matplotlib as plt
import numpy as np
import pandas as pd
import sklearn.datasets as dataset
import sklearn.preprocessing as preprocessing
import sklearn.tree as tree

# A. Penjelasan Implementasi

### Implementasi myMLP

20:05 Jan Meyer Implementasi myMLP dari kelompok kami menggunakan proses yang digunakan pada MLP pada umumnya, yaitu melakukan feed forward feedforward untuk menentukan keputusan yang ada berdasarkan data training yang dilatih dan data test yang diuji dan memperbaiki hasilnya dengan backpropagation, yaitu algoritma neural network yang memperbaiki weight setiap node dalam layer.

Pada implementasi MLP kami , logika komputasi didalam layer dibuat didalam Layer.py, terdapat class Layer yang mengandung informasi intrinsik sebuah Layer, misalnya jumlah node pada layer tersebut, weight dari layer sebelumnya, delta dan sebagainya. Selain itu terdapat juga class ActivationFunction yang merupakan enumerasi dari berbagai jenis fungsi aktivasi seperti fungsi linear dan sigmoid.

Class Layer akan menerima inputan berupa jumlah node, lapisan layer ke-berapa, dan jumlah node pada layer sebelumnya. Kemudian, setiap input yang masuk akan dicek apakah itu adalah layer pertama atau bukan pertama. Jika bukan pertama, akan ditambahkan bias. Kemudian, setiap layer yang terbentuk akan diberi fungsi aktivasi sesuai jenis layernya. Bagi layer pertama, fungsi aktivasi yang digunakan adalah linear, hal ini disebabkan dalam implementasi MLP kami, input layer tidak melakukan komputasi melainkan hanya meneruskan input kepada hidden layer. Bagi layer kedua dan layer output, fungsi aktivasi yang digunakan adalah sigmoid

Kemudian, setiap layer yang terbentuk akan diolah di dalam class MLP di file MLP.py dimana data-data akan selalu direset dengan flush dan diisi dengan delta sesuai dengan layernya melalui flushDelta. Kemudian, data yang telah masuk akan di-feed forward untuk nambahkan nilai dari node awal ke nilai akhir. Setelah itu, baru dijalankan algoritma backpropagation, yaitu mencari nilai delta atribut, delta hidden unit, dan delta weight untuk diterapkan pada setiap layer. Itu dilakukan untuk setiap data yang ada.

Setiap data diperoleh dari dataset yang discan dan memiliki dikelompokkan ke dalam mini-batch yang setiapnya berisi 10 data. flushDelta akan dipanggil setiap 1 mini-batch selesai diproses untuk meng-update weight. Setelah semua mini-batch selesai diproses, maka 1 epoch selesai.

Setelah itu, akan dijalankan predictionValue dan melakukan fungsi pembelajaran (learn) yang terhenti ketika mencapai max iteration, mencapai error minimum, atau mulai diverge.

# B. Hasil Eksekusi dan Perbandingan dengan hasil MLP sklearn 

In [2]:
# Read data from csv
data = pd.read_csv("iris.csv")
predictData = data
dataHead = list(data.columns)

# Shuffle data
data = data.sample(frac=1).reset_index(drop=True)

# Creates data by 10 (indexes of data)
dataSplitCount = 10
dataDict = {n: data.iloc[n:n+dataSplitCount, :] for n in range(0, len(data), dataSplitCount)}

## 1. myMLP

In [3]:
'''
Model generator
Generates layer to be put in MLP class and return MLP Model

Current layer:
    x
        x   x
    x
GK      x   x
    x
        x   x
    x

Abaikan GK
Layer paling kiri adalah keempat input dari 4 atribut iris.csv
Layer tengah adalah hidden layer
Layer output berfungsi sebagai yang dijelaskan di fungsi outputCheck
'''
def generateModel(learningRate):
    layer0 = Layer(4, 0, 4, ActivationFunction.linear)
    layer1 = Layer(3, 1, 4, ActivationFunction.sigmoid)
    layer2 = Layer(3, 2, 3, ActivationFunction.sigmoid)
    layers = []
    layers.append(layer0)
    layers.append(layer1)
    layers.append(layer2)
    return MLP(layers, learningRate)

# Do data training
'''
Create a function that returns the tuple of output node
'''
def nodeOutputCheck(str):
    if (str == "Versicolor"):
        return [0, 0, 1]
    elif (str == "Virginica"):
        return [0, 1, 0]
    elif (str == "Setosa"):
        return [1, 0, 0]
    else:
        return [1, 1, 1]

In [4]:
model = generateModel(0.1)
model.learn(dataDict, dataSplitCount, nodeOutputCheck, maxIteration=1000, minError=1, divergingMaxCount=10)

: 71, Wrong Prediction: 7, Total Case: 150, Error: 3.95062, Accuracy: 95.33%
Iteration: 72, Wrong Prediction: 7, Total Case: 150, Error: 3.91842, Accuracy: 95.33%
Iteration: 73, Wrong Prediction: 7, Total Case: 150, Error: 3.8838, Accuracy: 95.33%
Iteration: 74, Wrong Prediction: 7, Total Case: 150, Error: 3.84562, Accuracy: 95.33%
Iteration: 75, Wrong Prediction: 7, Total Case: 150, Error: 3.8039, Accuracy: 95.33%
Iteration: 76, Wrong Prediction: 7, Total Case: 150, Error: 3.76036, Accuracy: 95.33%
Iteration: 77, Wrong Prediction: 7, Total Case: 150, Error: 3.7183, Accuracy: 95.33%
Iteration: 78, Wrong Prediction: 6, Total Case: 150, Error: 3.68214, Accuracy: 96.0%
Iteration: 79, Wrong Prediction: 6, Total Case: 150, Error: 3.65619, Accuracy: 96.0%
Iteration: 80, Wrong Prediction: 6, Total Case: 150, Error: 3.64156, Accuracy: 96.0%
Iteration: 81, Wrong Prediction: 6, Total Case: 150, Error: 3.63419, Accuracy: 96.0%
Iteration: 82, Wrong Prediction: 6, Total Case: 150, Error: 3.6295, Ac

In [5]:
model.predict(predictData, nodeOutputCheck)

Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 0] True
Test Prediction:
[1, 0, 0] [1, 0, 

In [6]:
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))

Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[ 0.32148913  0.45764157  2.3153078  -3.28581657 -1.4545532 ]
 [-5.2479528  -4.92510752 -3.45121705  7.47247823  6.24807592]
 [ 1.95831773  0.77724573  1.46830511 -1.82105995 -1.81374146]]
Layer: 2
[[-3.67763966  6.58721345 -2.65448921  0.64507866]
 [-2.47828443 -2.17045227  5.52574239 -2.60876634]
 [ 2.86157331 -7.38211112 -5.57595907  1.05785671]]


## 2. MLP sklearn

In [7]:
df_norm = data[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
target = data[['variety']].replace(['Setosa','Versicolor','Virginica'],[0,1,2])
df = pd.concat([df_norm, target], axis=1)
testDf = df

df = df.sample(frac=1).reset_index(drop=True)

trainX = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
trainY = df[['variety']]

testX = df_norm
testY = target

In [8]:
mlp = skMLP(solver='sgd', alpha=0.1, learning_rate_init=0.1, hidden_layer_sizes=(1,3), activation='logistic', max_iter=1000, random_state=1, verbose=True)

mlp.fit(trainX, trainY)

tion 17, loss = 1.09841908
Iteration 18, loss = 1.09773342
Iteration 19, loss = 1.09718462
Iteration 20, loss = 1.09680759
Iteration 21, loss = 1.09659550
Iteration 22, loss = 1.09651289
Iteration 23, loss = 1.09651077
Iteration 24, loss = 1.09653993
Iteration 25, loss = 1.09656033
Iteration 26, loss = 1.09654608
Iteration 27, loss = 1.09648620
Iteration 28, loss = 1.09638238
Iteration 29, loss = 1.09624497
Iteration 30, loss = 1.09608845
Iteration 31, loss = 1.09592734
Iteration 32, loss = 1.09577325
Iteration 33, loss = 1.09563329
Iteration 34, loss = 1.09550983
Iteration 35, loss = 1.09540116
Iteration 36, loss = 1.09530295
Iteration 37, loss = 1.09520970
Iteration 38, loss = 1.09511612
Iteration 39, loss = 1.09501810
Iteration 40, loss = 1.09491316
Iteration 41, loss = 1.09480043
Iteration 42, loss = 1.09468040
Iteration 43, loss = 1.09455434
Iteration 44, loss = 1.09442385
Iteration 45, loss = 1.09429036
Iteration 46, loss = 1.09415490
Iteration 47, loss = 1.09401794
Iteration 48,

MLPClassifier(activation='logistic', alpha=0.1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(1, 3), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='sgd',
              tol=0.0001, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [9]:
print('Training set total iterations:', mlp.n_iter_)
print('           Training set score: ' + '{:.2%}'.format(mlp.score(trainX, trainY)))
print('            Training set loss: %.5f' % mlp.loss_)
print('             Number of output:', mlp.n_outputs_)
print('              Number of layer:', mlp.n_layers_)

print('\nLoss:')
print('Layer: 0\n', mlp.intercepts_[0])
print('Layer: 1\n', mlp.intercepts_[1])
print('Layer: 2\n', mlp.intercepts_[2])

print('\nWeight:')
print('Layer: 0\n', mlp.coefs_[0])
print('Layer: 1\n', mlp.coefs_[1])
print('Layer: 2\n', mlp.coefs_[2])

prediction = mlp.predict(testX)
print('\nTest accuracy: ' + '{:.2%}'.format(metrics.accuracy_score(prediction,testY)))

Training set total iterations: 622
           Training set score: 96.00%
            Training set loss: 0.21501
             Number of output: 3
              Number of layer: 4

Loss:
Layer: 0
 [2.95321137]
Layer: 1
 [ 1.71625189  3.99231484 -1.563244  ]
Layer: 2
 [ 2.39546079  0.71942836 -2.44235655]

Weight:
Layer: 0
 [[ 0.50803757]
 [ 1.89315219]
 [-3.23071367]
 [-4.24337168]]
Layer: 1
 [[-5.8821578  -5.74953572  4.67013753]]
Layer: 2
 [[-3.58808463 -1.68534776  5.47831888]
 [-6.80100172  2.06963982  4.43691932]
 [ 3.75845381  0.7633835  -4.98305845]]

Test accuracy: 96.00%


# C. Pembagian Tugas

| NIM      | Nama              | Tugas                                         |
|:--------:|:------------------|:----------------------------------------------|
| 13517014 | Yoel Susanto      | Feed Forward, Backpropagation, Data Structure |
| 13517065 | Andrian Cedric    | Feed Forward, Function, Documentation         |
| 13517131 | Jan Meyer Saragih | Feed Forward, Backpropagation, Data Structure |
| 13517137 | Vincent Budianto  | Feed Forward, Function, Documentation         |