# Tugas Besar 1D IF3270 - Machine Learning
------------------------------------------
##### NIM/Nama  : 13517014/Yoel Susanto | 13517065/Andrian Cedric | 13517131/Jan Meyer Saragih | 13517137/Vincent Budianto
##### Nama file : Tubes1D_13517014.ipynb
##### Topik     : Implementasi modul myMLP
##### Tanggal   : 28 February 2020
------------------------------------------

In [1]:
# Import any needs from C45
from decision_tree.DecisionTree import DecisionTree
from decision_tree.FitC45 import *

# Import any needs from MLP
from multilayer_perceptron.Layer import Layer, ActivationFunction
from multilayer_perceptron.MLP import MLP

# TenFoldCross for Testing
import TenFoldCross

from sklearn.neural_network import MLPClassifier as skMLP
from sklearn import metrics

import os
import matplotlib as plt
import numpy as np
import pandas as pd
import sklearn.datasets as dataset
import sklearn.preprocessing as preprocessing
import sklearn.tree as tree

## A. Accuracy Testing for ANN/DTL

In [2]:
tenfold = TenFoldCross.TenFoldCross("iris.csv")
tenfold.tenCrossFoldDTL()
tenfold.tenCrossFoldANN()

rror: 16.08529, Accuracy: 81.48%
Iteration: 21, Wrong Prediction: 23, Total Case: 135, Error: 15.84461, Accuracy: 82.96%
Iteration: 22, Wrong Prediction: 20, Total Case: 135, Error: 15.61021, Accuracy: 85.19%
Iteration: 23, Wrong Prediction: 19, Total Case: 135, Error: 15.37834, Accuracy: 85.93%
Iteration: 24, Wrong Prediction: 14, Total Case: 135, Error: 15.14608, Accuracy: 89.63%
Iteration: 25, Wrong Prediction: 13, Total Case: 135, Error: 14.91119, Accuracy: 90.37%
Iteration: 26, Wrong Prediction: 13, Total Case: 135, Error: 14.67199, Accuracy: 90.37%
Iteration: 27, Wrong Prediction: 12, Total Case: 135, Error: 14.42727, Accuracy: 91.11%
Iteration: 28, Wrong Prediction: 11, Total Case: 135, Error: 14.17623, Accuracy: 91.85%
Iteration: 29, Wrong Prediction: 12, Total Case: 135, Error: 13.91842, Accuracy: 91.11%
Iteration: 30, Wrong Prediction: 12, Total Case: 135, Error: 13.65369, Accuracy: 91.11%
Iteration: 31, Wrong Prediction: 11, Total Case: 135, Error: 13.38216, Accuracy: 91.85%

## B. Splitting Data

In [21]:
data = pd.read_csv("dataset/iris.csv")
trainingData = data.sample(frac=0.9)
testingData = data.drop(trainingData.index)


sepal.length  sepal.width  petal.length  petal.width     variety
3             4.6          3.1           1.5          0.2      Setosa
103           6.3          2.9           5.6          1.8   Virginica
34            4.9          3.1           1.5          0.2      Setosa
0             5.1          3.5           1.4          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa
..            ...          ...           ...          ...         ...
87            6.3          2.3           4.4          1.3  Versicolor
44            5.1          3.8           1.9          0.4      Setosa
39            5.1          3.4           1.5          0.2      Setosa
53            5.5          2.3           4.0          1.3  Versicolor
97            6.2          2.9           4.3          1.3  Versicolor

[135 rows x 5 columns]


## C. DTL modeling

In [23]:
dataHead, data, dataRaw = getCSVData(trainingData)
prune(dataHead, data, dataRaw)

ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>

# B. Hasil Eksekusi dan Perbandingan dengan hasil MLP sklearn 

In [12]:
# Read data from csv
data = pd.read_csv("iris.csv")
predictData = data
dataHead = list(data.columns)

# Shuffle data
data = data.sample(frac=1).reset_index(drop=True)

# Creates data by 10 (indexes of data)
dataSplitCount = 10
dataDict = {n: data.iloc[n:n+dataSplitCount, :] for n in range(0, len(data), dataSplitCount)}

FileNotFoundError: [Errno 2] File iris.csv does not exist: 'iris.csv'

## 1. myMLP

In [13]:
'''
Model generator
Generates layer to be put in MLP class and return MLP Model

Current layer:
    x
        x   x
    x
GK      x   x
    x
        x   x
    x

Abaikan GK
Layer paling kiri adalah keempat input dari 4 atribut iris.csv
Layer tengah adalah hidden layer
Layer output berfungsi sebagai yang dijelaskan di fungsi outputCheck
'''
def generateModel(learningRate):
    layer0 = Layer(4, 0, 4, ActivationFunction.linear)
    layer1 = Layer(3, 1, 4, ActivationFunction.sigmoid)
    layer2 = Layer(3, 2, 3, ActivationFunction.sigmoid)
    layers = []
    layers.append(layer0)
    layers.append(layer1)
    layers.append(layer2)
    return MLP(layers, learningRate)

# Do data training
'''
Create a function that returns the tuple of output node
'''
def nodeOutputCheck(str):
    if (str == "Versicolor"):
        return [0, 0, 1]
    elif (str == "Virginica"):
        return [0, 1, 0]
    elif (str == "Setosa"):
        return [1, 0, 0]
    else:
        return [1, 1, 1]

In [14]:
model = generateModel(0.1)
model.learn(dataDict, dataSplitCount, nodeOutputCheck, maxIteration=1000, minError=1, divergingMaxCount=10)

NameError: name 'dataDict' is not defined

In [15]:
model.predict(predictData, nodeOutputCheck)

NameError: name 'predictData' is not defined

In [16]:
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))

Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[ 0.08197561  0.43776807 -0.72186181  0.36159561  0.92065792]
 [ 0.05895018 -0.44874244 -0.89061159 -0.96905961  0.90656318]
 [-0.82396956  0.45459854  0.30175562 -0.58689189 -0.21440845]]
Layer: 2
[[ 0.33936237 -0.61159273  0.20348724 -0.07555128]
 [ 0.12618172 -0.2244457   0.44527743  0.00568612]
 [-0.15663429  0.37884274  0.898561    0.88760965]]


## 2. MLP sklearn

In [17]:
df_norm = data[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
target = data[['variety']].replace(['Setosa','Versicolor','Virginica'],[0,1,2])
df = pd.concat([df_norm, target], axis=1)
testDf = df

df = df.sample(frac=1).reset_index(drop=True)

trainX = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
trainY = df[['variety']]

testX = df_norm
testY = target

In [18]:
mlp = skMLP(solver='sgd', alpha=0.1, learning_rate_init=0.1, hidden_layer_sizes=(1,3), activation='logistic', max_iter=1000, random_state=1, verbose=True)

mlp.fit(trainX, trainY)

tion 17, loss = 1.09841908
Iteration 18, loss = 1.09773342
Iteration 19, loss = 1.09718462
Iteration 20, loss = 1.09680759
Iteration 21, loss = 1.09659550
Iteration 22, loss = 1.09651289
Iteration 23, loss = 1.09651077
Iteration 24, loss = 1.09653993
Iteration 25, loss = 1.09656033
Iteration 26, loss = 1.09654608
Iteration 27, loss = 1.09648620
Iteration 28, loss = 1.09638238
Iteration 29, loss = 1.09624497
Iteration 30, loss = 1.09608845
Iteration 31, loss = 1.09592734
Iteration 32, loss = 1.09577325
Iteration 33, loss = 1.09563329
Iteration 34, loss = 1.09550983
Iteration 35, loss = 1.09540116
Iteration 36, loss = 1.09530295
Iteration 37, loss = 1.09520970
Iteration 38, loss = 1.09511612
Iteration 39, loss = 1.09501810
Iteration 40, loss = 1.09491316
Iteration 41, loss = 1.09480043
Iteration 42, loss = 1.09468040
Iteration 43, loss = 1.09455434
Iteration 44, loss = 1.09442385
Iteration 45, loss = 1.09429036
Iteration 46, loss = 1.09415490
Iteration 47, loss = 1.09401794
Iteration 48,

MLPClassifier(activation='logistic', alpha=0.1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(1, 3), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='sgd',
              tol=0.0001, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [19]:
print('Training set total iterations:', mlp.n_iter_)
print('           Training set score: ' + '{:.2%}'.format(mlp.score(trainX, trainY)))
print('            Training set loss: %.5f' % mlp.loss_)
print('             Number of output:', mlp.n_outputs_)
print('              Number of layer:', mlp.n_layers_)

print('\nLoss:')
print('Layer: 0\n', mlp.intercepts_[0])
print('Layer: 1\n', mlp.intercepts_[1])
print('Layer: 2\n', mlp.intercepts_[2])

print('\nWeight:')
print('Layer: 0\n', mlp.coefs_[0])
print('Layer: 1\n', mlp.coefs_[1])
print('Layer: 2\n', mlp.coefs_[2])

prediction = mlp.predict(testX)
print('\nTest accuracy: ' + '{:.2%}'.format(metrics.accuracy_score(prediction,testY)))

Training set total iterations: 622
           Training set score: 96.00%
            Training set loss: 0.21501
             Number of output: 3
              Number of layer: 4

Loss:
Layer: 0
 [2.95321137]
Layer: 1
 [ 1.71625189  3.99231484 -1.563244  ]
Layer: 2
 [ 2.39546079  0.71942836 -2.44235655]

Weight:
Layer: 0
 [[ 0.50803757]
 [ 1.89315219]
 [-3.23071367]
 [-4.24337168]]
Layer: 1
 [[-5.8821578  -5.74953572  4.67013753]]
Layer: 2
 [[-3.58808463 -1.68534776  5.47831888]
 [-6.80100172  2.06963982  4.43691932]
 [ 3.75845381  0.7633835  -4.98305845]]

Test accuracy: 96.00%


# C. Pembagian Tugas

| NIM      | Nama              | Tugas                                         |
|:--------:|:------------------|:----------------------------------------------|
| 13517014 | Yoel Susanto      | Feed Forward, Backpropagation, Data Structure |
| 13517065 | Andrian Cedric    | Feed Forward, Function, Documentation         |
| 13517131 | Jan Meyer Saragih | Feed Forward, Backpropagation, Data Structure |
| 13517137 | Vincent Budianto  | Feed Forward, Function, Documentation         |