# Tugas Besar 1D IF3270 - Machine Learning
------------------------------------------
##### NIM/Nama  : 13517014/Yoel Susanto | 13517065/Andrian Cedric | 13517131/Jan Meyer Saragih | 13517137/Vincent Budianto
##### Nama file : Tubes1D_13517014.ipynb
##### Topik     : Implementasi modul C45 dan MLP dan Perbandingan
##### Tanggal   : 20 Maret 2020
------------------------------------------

In [12]:
# Import any needs from C45
from decision_tree.DecisionTree import DecisionTree
from decision_tree.FitC45 import *

# Import any needs from MLP
from multilayer_perceptron.Layer import Layer, ActivationFunction
from multilayer_perceptron.MLP import MLP
from multilayer_perceptron.main import *

from sklearn.neural_network import MLPClassifier as skMLP
from sklearn import metrics

import os
import matplotlib as plt
import numpy as np
import pandas as pd
import sklearn.datasets as dataset
import sklearn.preprocessing as preprocessing
import sklearn.tree as tree

## A. Accuracy Testing for ANN/DTL

### DTL

In [14]:
from TenFoldCross import TenFoldCross

tenfold = TenFoldCross("iris.csv")
trainingTimeList, accuracyList = tenfold.tenCrossFoldDTL()


Ten Fold Cross Valudation DTL Iteration: 0
Ten Fold Cross Valudation DTL Iteration: 1
Ten Fold Cross Valudation DTL Iteration: 2
Ten Fold Cross Valudation DTL Iteration: 3
Ten Fold Cross Valudation DTL Iteration: 4
Ten Fold Cross Valudation DTL Iteration: 5
Ten Fold Cross Valudation DTL Iteration: 6
Ten Fold Cross Valudation DTL Iteration: 7
Ten Fold Cross Valudation DTL Iteration: 8
Ten Fold Cross Valudation DTL Iteration: 9
Elapsed Time
[0.04901623725891113, 0.053998708724975586, 0.057999610900878906, 0.029997825622558594, 0.03300070762634277, 0.024996042251586914, 0.037001609802246094, 0.025045156478881836, 0.04199957847595215, 0.05095195770263672]
Accuracy
[0.8666666666666667, 0.9333333333333333, 0.8666666666666667, 1.0, 0.9333333333333333, 1.0, 0.9333333333333333, 1.0, 0.8666666666666667, 1.0]


In [16]:
timeElapsedDTL = 0
accuracyDTL = 0

for i in range(10):
    timeElapsedDTL += trainingTimeList[i] 
    accuracyDTL += accuracyList[i]

print("Time elapsed")
print(trainingTimeList)
print("Time elapsed average", timeElapsedDTL/10)

print("\n Accuracy")
print(accuracyList)
print("Accuracy average", accuracyDTL / 10)

Time elapsed
[0.04901623725891113, 0.053998708724975586, 0.057999610900878906, 0.029997825622558594, 0.03300070762634277, 0.024996042251586914, 0.037001609802246094, 0.025045156478881836, 0.04199957847595215, 0.05095195770263672]
Time elapsed average 0.04040074348449707

 Accuracy
[0.8666666666666667, 0.9333333333333333, 0.8666666666666667, 1.0, 0.9333333333333333, 1.0, 0.9333333333333333, 1.0, 0.8666666666666667, 1.0]
Accuracy average 0.9400000000000001


### ANN

In [17]:
trainingTimeList, accuracyList = tenfold.tenCrossFoldANN()

Ten Fold Cross Valudation ANN Iteration: 0
Ten Fold Cross Valudation ANN Iteration: 1
Ten Fold Cross Valudation ANN Iteration: 2
Ten Fold Cross Valudation ANN Iteration: 3
Ten Fold Cross Valudation ANN Iteration: 4
Ten Fold Cross Valudation ANN Iteration: 5
Ten Fold Cross Valudation ANN Iteration: 6
Ten Fold Cross Valudation ANN Iteration: 7
Ten Fold Cross Valudation ANN Iteration: 8
Ten Fold Cross Valudation ANN Iteration: 9
Elapsed Time
[6.313996315002441, 6.053034067153931, 5.980997323989868, 6.092752933502197, 6.19000244140625, 6.1600446701049805, 6.097994327545166, 6.343969821929932, 6.297055006027222, 6.23100209236145]
Accuracy
[0.6, 0.7333333333333333, 0.7333333333333333, 0.9333333333333333, 0.4, 0.2, 0.6, 0.9333333333333333, 0.2, 0.4666666666666667]


In [18]:
timeElapsedANN = 0
accuracyANN = 0

for i in range(10):
    timeElapsedANN += trainingTimeList[i] 
    accuracyANN += accuracyList[i]

print("Time elapsed")
print(trainingTimeList)
print("Time elapsed average", timeElapsedANN/10)

print("\n Accuracy")
print(accuracyList)
print("Accuracy average", accuracyANN / 10)


Time elapsed
[6.313996315002441, 6.053034067153931, 5.980997323989868, 6.092752933502197, 6.19000244140625, 6.1600446701049805, 6.097994327545166, 6.343969821929932, 6.297055006027222, 6.23100209236145]
Time elapsed average 6.176084899902344

 Accuracy
[0.6, 0.7333333333333333, 0.7333333333333333, 0.9333333333333333, 0.4, 0.2, 0.6, 0.9333333333333333, 0.2, 0.4666666666666667]
Accuracy average 0.5800000000000001


## B. Splitting Data

In [19]:
data = pd.read_csv("dataset/iris.csv")
trainingData = data.sample(frac=0.9)
testingData = data.drop(trainingData.index)


## C. DTL modeling

In [21]:
## Load DTL model from training data
loadRules(trainingData)


xml Result :
<petal.length flag="r" impurity="32/39" value="2.45">
    <petal.width flag="l" impurity="4/38" value="1.75">
      <sepal.length flag="l" impurity="3/38" value="7.05">
        <sepal.width flag="l" impurity="3/19" value="2.8499999999999996">Versicolor</sepal.width>
        <sepal.width flag="r" impurity="19" value="2.8499999999999996">Versicolor</sepal.width>
      </sepal.length><sepal.length flag="r" impurity="1" value="7.05">Virginica</sepal.length>
    </petal.width><petal.width flag="r" impurity="28/1" value="1.75">
      <sepal.length flag="l" impurity="7/1" value="6.25">
        <sepal.width flag="l" impurity="7" value="3.05">Virginica</sepal.width>
        <sepal.width flag="r" impurity="1" value="3.05">Versicolor</sepal.width>
      </sepal.length><sepal.length flag="r" impurity="21" value="6.25">Virginica</sepal.length>
    </petal.width>
  </petal.length>

Rules :
[['petal.length <= 2.45', 'Setosa'], ['petal.width <= 1.75', 'Versicolor'], ['petal.width <= 1.75

## D. ANN Modeling

In [22]:
data = trainingData
predictData = data
dataHead = list(data.columns)

model = learn(data, dataHead, predictData, False, True)

# Test result
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))

Saving newest ANN model!
Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[-0.78616133 -1.19244754 -0.43123358  2.43502836  0.89499363]
 [-0.1348321  -1.21436515  0.20583955  0.0292471  -0.44996986]
 [-0.60502158 -0.0694131  -0.81994818 -0.31490774 -0.85162207]]
Layer: 2
[[ 1.74290583 -4.39324144 -0.87513203  0.97046311]
 [-2.58904608  2.5616174  -0.35749431  0.35769296]
 [-1.57014303  1.6731346   0.85607469 -0.42738742]]


## E. DTL Model Load and Accuracy Testing

In [34]:
# Init
rules = []
modelRules = []
accuracyList = []
dataCopy = cp.copy(testingData)
dataHead = list(dataCopy.columns)
txtFile = "RuleList.txt"

# Load
with open(txtFile, "rb") as f:
        rules = pickle.load(f)

for i in range(len(rules)):
                modelRules.append(createRule(rules[i]))
errorCount = getErrorCountExternal(testingData, modelRules, dataHead)
accuracyDTL = (len(testingData) - errorCount) / len(testingData)

## F. ANN Model Load and Accuracy Testing

In [35]:
data = testingData
predictData = data
dataHead = list(data.columns)
accuracyListANN = []

model = learn(data, dataHead, predictData)

# Test result
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))
    accuracyANN = model.predict(testingData, nodeOutputCheckExternal)
    accuracyListANN.append(accuracyANN)



Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[-0.79892511 -0.33525362 -0.49511272  1.48168924 -0.59643061]
 [ 1.0777076  -0.01746116  0.98936153 -0.77202859 -1.12907695]
 [ 0.65729743  0.59216448  0.63150836 -0.6692684   0.91796501]]
Layer: 2
[[ 0.08266413 -1.36225922  1.40465036 -0.44986209]
 [-0.39154228  1.12741974 -1.71661818  0.49593419]
 [-0.94255015  0.03717847 -0.88987529 -0.55873727]]


## G. Accuarcy Test DTL 

In [47]:
print(accuracyDTL)

0.9333333333333333


## H. Accuracy Test ANN

In [40]:
print(accuracyANN)

0.8666666666666667
