# Tugas Besar 1D IF3270 - Machine Learning
------------------------------------------
##### NIM/Nama  : 13517014/Yoel Susanto | 13517065/Andrian Cedric | 13517131/Jan Meyer Saragih | 13517137/Vincent Budianto
##### Nama file : Tubes1D_13517014.ipynb
##### Topik     : Implementasi modul C45 dan MLP dan Perbandingan
##### Tanggal   : 20 Maret 2020
------------------------------------------

In [2]:
# Import any needs from C45
from decision_tree.DecisionTree import DecisionTree
from decision_tree.FitC45 import *

# Import any needs from MLP
from multilayer_perceptron.Layer import Layer, ActivationFunction
from multilayer_perceptron.MLP import MLP
from multilayer_perceptron.main import *

from sklearn.neural_network import MLPClassifier as skMLP
from sklearn import metrics

import os
import matplotlib as plt
import numpy as np
import pandas as pd
import sklearn.datasets as dataset
import sklearn.preprocessing as preprocessing
import sklearn.tree as tree

## A. Accuracy Testing for ANN/DTL

In [22]:
import TenFoldCross

# timeElapsedDTL = 0
# accuracyDTL = 0

# for i in range(10):
#     timeElapsedDTL += trainingTimeList[i] 
#     accuracyDTL += accuracyList[i]
# print(timeElapsedDTL/10)

NameError: name 'trainingTimeList' is not defined

In [17]:
# # Time Elapsed for DTL TenFoldCross
# timeElapsedDTL = 0
# accuracyDTL = 0

# # Time Elapsed for ANN TenFoldCross
# timeElapsedANN = 0
# accuracyANN = 0

# for i in range(10):
#     timeElapsedDTL += TenFoldCross.tenCrossFoldDTL.trainingTimeList[i] 
#     accuracyDTL += tenCrossFoldDTL.accuracyList[i]


NameError: name 'TenFoldCross' is not defined

## B. Splitting Data

In [3]:
data = pd.read_csv("dataset/iris.csv")
trainingData = data.sample(frac=0.9)
testingData = data.drop(trainingData.index)


## C. DTL modeling

In [4]:
## Load DTL model from training data
loadRules(trainingData)


xml Result :
<petal.length value="2.45" flag="r" impurity="34/37">
    <petal.width value="1.75" flag="l" impurity="3/36">
      <sepal.length value="7.05" flag="l" impurity="2/36">
        <sepal.width value="2.8499999999999996" flag="l" impurity="2/21">Versicolor</sepal.width>
        <sepal.width value="2.8499999999999996" flag="r" impurity="15">Versicolor</sepal.width>
      </sepal.length><sepal.length value="7.05" flag="r" impurity="1">Virginica</sepal.length>
    </petal.width><petal.width value="1.75" flag="r" impurity="31/1">
      <sepal.length value="6.25" flag="l" impurity="8/1">
        <sepal.width value="3.05" flag="l" impurity="7">Virginica</sepal.width>
        <sepal.width value="3.05" flag="r" impurity="1/1">Virginica</sepal.width>
      </sepal.length><sepal.length value="6.25" flag="r" impurity="23">Virginica</sepal.length>
    </petal.width>
  </petal.length>

Rules :
[['petal.length <= 2.45', 'Setosa'], ['sepal.length <= 7.05', 'sepal.width <= 2.8499999999999996

## D. ANN Modeling

In [5]:
data = trainingData
predictData = data
dataHead = list(data.columns)

model = learn(data, dataHead, predictData)

# Test result
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))

Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[ 0.96212765 -0.84474871 -0.73531242 -0.56848295  0.58609046]
 [ 0.20939021  0.76941707  0.86320737 -0.41498976 -0.37766324]
 [-0.39402694 -0.21114903 -1.81743503  2.48645768  0.10191722]]
Layer: 2
[[ 0.82951035 -0.74336412  0.92219914 -3.99778146]
 [-1.20181382  0.52825348 -0.9365832   2.01181655]
 [-0.98824514 -0.91568416 -1.00959229  2.03664288]]


## E. DTL Model Load 

In [6]:
# Init
rules = []
modelRules = []
accuracyList = []
dataCopy = cp.copy(testingData)
dataHead = list(dataCopy.columns)
txtFile = "RuleList.txt"

# Load
with open(txtFile, "rb") as f:
        rules = pickle.load(f)

for i in range(len(rules)):
                modelRules.append(createRule(rules[i]))
errorCount = getErrorCountExternal(testingData, modelRules, dataHead)
accuracyDTL = (len(testingData) - errorCount) / len(testingData)

## F. ANN Model Load

In [13]:
data = testingData
predictData = data
dataHead = list(data.columns)
accuracyListANN = []

model = learn(data, dataHead, predictData)

# Test result
for i in range(len(model.layers)):
    print("Layer: {}".format(i))
    print(np.matrix(model.layers[i].weight))
    accuracyANN = model.predict(testingData, nodeOutputCheckExternal)
    accuracyListANN.append(accuracyANN)



Layer: 0
[[1]
 [1]
 [1]
 [1]]
Layer: 1
[[ 0.76310784  0.0674449  -0.5140741   0.13309517  0.71149454]
 [ 0.75995319  0.85502309  0.03810182 -0.66841674  0.65536424]
 [ 0.96577627 -0.81403369 -0.18943507 -0.74373745 -0.04564464]]
Layer: 2
[[-0.1767305  -0.99511286 -0.78617254 -0.2595553 ]
 [ 0.2098321  -0.41756875  0.31771466  0.33151511]
 [-0.43832987 -0.31469785 -0.05616975  0.68053917]]


## G. Accuarcy Test DTL 

In [16]:
print(accuracyDTL)

0.6


## H. Accuracy Test ANN

In [15]:
print(accuracyANN)

0.5333333333333333
